apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "goadmission.mritd.me"
  namespace: kube-addons
webhooks:
  - name: "goadmission.mritd.me"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["*"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        name: "goadmission"
        namespace: "kube-addons"
        path: /print
      caBundle: ${CA_BUNDLE}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        addon-controller: goadmission